### ISSUE TITLE
Exception Occurs Retreiving Tracks, Albums, etc. for Spotify within Mopidy (Iris).

### ISSUE THREAD

**Issue by KeepSummerSaf3** [hassio-addons/addon-mopidy#53]
# Problem/Motivation

```
INFO     2020-11-26 02:25:24,568 [422:SpotifyBackend-7] mopidy_spotify.lookup
  Failed to lookup 'spotify:directory': Could not parse 'spotify:directory' as a Spotify URI
ERROR    2020-11-26 02:25:24,596 [422:Core-14] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 181, in get_images
    if future.get() is None:
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 23, in get_images
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 23, in <genexpr>
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 45, in _parse_uri
    uri_type, uri_id = parsed_uri.path.split(":")[:2]
ValueError: not enough values to unpack (expected 2, got 1)
INFO     2020-11-26 02:25:27,370 [422:SpotifyBackend-7] mopidy_spotify.lookup
  Failed to lookup 'spotify:your': Could not parse 'spotify:your' as a Spotify URI
ERROR    2020-11-26 02:25:27,405 [422:Core-14] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 181, in get_images
    if future.get() is None:
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 23, in get_images
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 23, in <genexpr>
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 59, in _parse_uri
    raise ValueError(f"Could not parse {repr(uri)} as a Spotify URI")
ValueError: Could not parse 'spotify:your:tracks' as a Spotify URI
INFO     2020-11-26 02:25:28,720 [422:SpotifyBackend-7] mopidy_spotify.lookup
  Failed to lookup 'spotify:your:tracks': Could not parse 'spotify:your:tracks' as a Spotify URI
ERROR    2020-11-26 02:25:31,266 [422:Core-14] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 181, in get_images
    if future.get() is None:
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 23, in get_images
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 23, in <genexpr>
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/images.py", line 45, in _parse_uri
    uri_type, uri_id = parsed_uri.path.split(":")[:2]
ValueError: not enough values to unpack (expected 2, got 1)
```

## Expected behavior

Sqlite database/table may not exist. Empty records possibly?
Try/except handling in the event of an invalid data. 

## Actual behavior

Exception causes the webUI to not provide any usable data. Addon is useless.

## Steps to reproduce

Valid Spotify account to test.

## Proposed changes

See **expected behavior**. Would this need to be possibly pushed back as an issue against the Mopidy or Iris repos?

**Comment by SilverWx** [comment]
Same issue for me

**Comment by brammittendorff** [comment]
Could you please provide us with a config? (remove the user + password creds, but at least how youre config looks like?)
